language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda/etc/profile.d/conda.sh
    - conda config --set always_yes yes
    - conda config --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    - conda env create --file dev_env.yml
    - conda activate Sandbox
